services:
  app:
    container_name: laravel-tutorial-app
    build: ./docker/php
    volumes:
      - .:/var/www
    ports:
      - 5173:5173

  nginx:
    image: nginx
    container_name: laravel-tutorial-nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel-tutorial-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mailpit:
    container_name: laravel-tutorial-mailpit
    build: ./docker/mailpit
    ports:
      - 1025:1025/tcp
      - 8025:8025/tcp
